export interface ficha {
  id_ficha: number;
  forc: number;
  dest: number;
  consti: number;
  inte: number;
  sab: number;
  car: number;
  forcMod: number;
  destMod: number;
  constiMod: number;
  inteMod: number;
  sabMod: number;
  carMod: number;
  bonusProef: number;
  inspira: number;
  sabPassiva: number;
  nomePerso: string;
  antecendente: string;
  exp: number;
  nivel: number;
  classe: string;
  alinhamento: string;
  raca: string;
  idiomas_Proeficiencias: string | null;
  iniciativa: number;
  qtd_DadosVida: number;
  ideais: string | null;
  vinculos: string | null;
  tracosPerso: string | null;
  fraquezas: string | null;
  caractHabilidades: string | null;
  pvTotais: number;
  dadoVida: string;
  deslocamento: number;
  pCobre: number;
  pPrata: number;
  pOuro: number;
  pEletro: number;
  pPlatina: number;
  descAtaque: string | null;
  descEquip: string | null;
  olhos: string;
  cabelos: string;
  idade: number;
  altura: number;
  peso: number;
  pele: string;
  aparencia: string | null;
  aliadosOrg: string | null;
  outrasCaract: string | null;
  historia: string | null;
  tesouro: string | null;
  publica: boolean;
  usuario: number;
}